language: node_js
node_js:
  - "8"
  - "10"
  - "12"
env:
  global:
    - CC_TEST_REPORTER_ID=c247365a9a7270a8a0e198746a58db6228982a5fcec2f9d94dc081dba241e0a0
matrix:
  allow_failures:
    - node_js: "8"
    - node_js: "12"
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run lint
  - npm run test:coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
